# Generated by Django 6.0.4 on 2026-05-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condominium',
            options={'verbose_name': 'Condominio', 'verbose_name_plural': 'Condominios'},
        ),
        migrations.AlterField(
            model_name='condominium',
            name='address',
            field=models.TextField(blank=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='condominiums/logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefono'),
        ),
    ]
