# Generated by Django 6.0.4 on 2026-05-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto mensual'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del propietario'),
        ),
        migrations.AddField(
            model_name='property',
            name='tenant_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio del inquilino'),
        ),
    ]
