# Generated by Django 6.0.4 on 2026-06-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_monthly_fee_property_owner_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rent_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Alquiler'),
        ),
        migrations.AlterField(
            model_name='property',
            name='monthly_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto mensual (Condominio)'),
        ),
    ]
