# Generated by Django 6.0.4 on 2026-05-07 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiums', '0002_alter_condominium_options_alter_condominium_address_and_more'),
        ('properties', '0001_initial'),
        ('residents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='residentprofile',
            options={'verbose_name': 'Perfil de residente', 'verbose_name_plural': 'Perfiles de residentes'},
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='condominium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='condominiums.condominium', verbose_name='Condominio'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='document_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Documento de identidad'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=150, verbose_name='Contacto de emergencia'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='properties.property', verbose_name='Propiedad'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='resident_type',
            field=models.CharField(choices=[('owner', 'Propietario'), ('tenant', 'Arrendatario'), ('family_member', 'Familiar')], max_length=30, verbose_name='Tipo de residente'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resident_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
