# Generated by Django 6.0.4 on 2026-05-16 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visitante', models.CharField(max_length=150)),
                ('motivo', models.CharField(choices=[('Visita social', 'Visita social'), ('Delivery', 'Delivery'), ('Servicio técnico', 'Servicio técnico'), ('Otros', 'Otros')], default='Visita social', max_length=50)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_residente', models.CharField(max_length=150)),
                ('apartamento_destino', models.CharField(max_length=20)),
                ('hora_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
    ]
