# Generated by Django 6.0.4 on 2026-04-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('maintenance', 'Mantenimiento'), ('assembly', 'Asamblea'), ('security', 'Seguridad'), ('common', 'Áreas Comunes')], default='maintenance', max_length=20),
            preserve_default=False,
        ),
    ]
