# Generated by Django 6.0.4 on 2026-04-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('MENSUALIDAD', 'Mensualidad'), ('ABONO', 'Abono')], max_length=20)),
                ('estado', models.CharField(choices=[('COBRADO', 'Cobrado'), ('PENDIENTE', 'Pendiente'), ('MOROSO', 'Moroso')], default='PENDIENTE', max_length=20)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
