# Generated by Django 6.0.4 on 2026-06-06 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_resident_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('MANTENIMIENTO', 'Mantenimiento'), ('SEGURIDAD', 'Seguridad'), ('SERVICIOS', 'Servicios'), ('ADMINISTRACION', 'Administración'), ('OTROS', 'Otros')], default='OTROS', max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('torre', models.CharField(max_length=100)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
